
Exception caught at 2024-11-14 23:11:35.922789:
Traceback (most recent call last):
  File "/home/nakota/Documents/cpre381-proj1/cpre381-toolflow/internal/snthpy/synthesis.py", line 89, in <module>
    main(args)
  File "/home/nakota/Documents/cpre381-proj1/cpre381-toolflow/internal/snthpy/synthesis.py", line 38, in main
    if not os.path.isdir(quartus_path):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 42, in isdir
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

Exception caught at 2024-11-14 23:11:43.855316:
Traceback (most recent call last):
  File "/home/nakota/Documents/cpre381-proj1/cpre381-toolflow/internal/snthpy/synthesis.py", line 89, in <module>
    main(args)
  File "/home/nakota/Documents/cpre381-proj1/cpre381-toolflow/internal/snthpy/synthesis.py", line 38, in main
    if not os.path.isdir(quartus_path):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 42, in isdir
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
